apiVersion: policy.jspolicy.com/v1beta1
kind: JsPolicyBundle
metadata:
  name: validate-xp-mrs.mycompany.tld
spec:
  bundle: H4sIAAAAAAAAA6VTwW7bMAz9FdUHQ8I8IdiGYYuhBtjQY9Gh2C0LCkWmE7Ue5dFyt8D1v4926rQBkl12MUTxieR7fJZSmcsuaRsQTSTvYpI/WhJgug/vP88lZDTkb9b34KIuoPQI3yjUQHEnKUvu7qC5DkVbQZJ1j7ZqYX4x61VGmgNf2AjXFu0GiltoQksOGvMYfCFm/0KULbroA0pQnQvYREFmucoJYksoYKFpgi50GejKuq2UwGOCXtuG8w8ei4X+aSMnki+te4CYqDQlXbcN33wlsEN9EUoxQMV6hAjfCAxR2KoKv6FIVK+YSN9nH999+h8lLJHdGdKAPKyD77saOCoAdzd4RRTolSZHtwcdtNZHUmg+Ohu1retqxyrlpCvATdxeztJ0KCGTW/jVAsM58sAMwdlhx8w4bkGUYeDocSNgbDX/gW+TN6Tvg0eZDIFSfXY88uutTKvoD/ROZZ+elque9SPT9fkEEEGi6gaPRUNLXOW+lHv6F8ZE9fw2avhTB4rN6EY7Ik33fDfv+v7gBk5Im9kJnwX1EvTDYxy6y9Hme2djfnqJcHaJ+SR9kOwFlUU+8O/BnQztddZhLJkfb1DGsyaXVjc1OJZZSZXv5Zgos+ZypC08ClRxaVcG+ZOjfhkwTU+ziGdZjJ3+AoQmIKvwAwAA
